#!/bin/sh

set -eu

{
    : "${XDG_CONFIG_HOME:=$HOME/.config}"
    : "${XDG_CACHE_HOME:=$HOME/.cache}"
    : "${GITHUB_TOKEN:=}"

    readonly WALLPAPER_DIR="$HOME/Pictures"

    readonly GITHUB_BASE_URL=https://github.com
    readonly GITHUB_OWNER=envyj020
    readonly GITHUB_REPOSITORY=dotfiles
    readonly GITHUB_BRANCH=main

    readonly BOLD='\033[1m'
    readonly GREEN='\033[1;32m'
    readonly RED='\033[1;31m'
    readonly BLUE='\033[1;36m'
    readonly YELLOW='\033[0;33m'
    readonly NC='\033[0m'

    info() {
        printf "${BLUE}🛈 INFO:${NC} ${BOLD}%b${NC}\n" "$*"
    }

    warn() {
        printf "${YELLOW}‼ WARNING:${NC} ${BOLD}%b${NC}\n" "$*"
    }

    error() {
        printf "${RED}✖ ERROR:${NC} ${BOLD}%b${NC}\n" "$*" >&2
        exit 1
    }

    row() (
        printf '%.0s─' $(seq 1 "$(tput cols)")
    )

    checkout() {
        [ -d "$2" ] || {
            info "Cloning $1 into: $2"
            GIT_LFS_SKIP_SMUDGE=1 git \
                -c advice.detachedHead=0 \
                -c core.autocrlf=false clone \
                --branch "$3" --depth 1 --recursive \
                --quiet "$1" "$2" || error "Couldn't clone $1 repository into $2"
        }
    }

    require_os() {
        OS_NAME=$(awk -F'=' '/^ID=/ {print $2}' /etc/os-release)
        case $OS_NAME in
        fedora | ubuntu | debian) return 0 ;;
        *) error "Your OS distribution: $OS_NAME is not supported" ;;
        esac
    }

    require_cmd() {
        for cmd in "$@"; do
            if ! command -v "$cmd" >/dev/null 2>&1; then
                error "$cmd is required but not installed."
            fi
        done
    }

    require_dependencies() {
        [ -t 0 ] || error "Interactive tty required."
        require_cmd "git" "git-lfs" "make"
        require_token
    }

    require_token() {
        [ -n "$GITHUB_TOKEN" ] && return 0
        row
        warn "${BOLD}MISSING ${RED}GITHUB_TOKEN${NC}"
        info "It looks like you have not exported your ${BLUE}GITHUB_TOKEN${NC}, ${BOLD}please note"
        info "Github API rate limits will likely cause the bootstrap process to crash."
        info "Please run: ${GREEN}export GITHUB_TOKEN=\$(<\"\$HOME/.GITHUB_TOKEN\")${NC} ${BOLD}and execute"
        info "again this script. Find more information at the link below:"
        info "${BLUE}https://envyj020.github.io/dotfiles/guides/installation/#prerequisites${NC}"
        row

        info "Press [c] to continue anyway or [e] to exit:"
        while true; do
            read -r choice
            case $choice in
            [cC])
                return 0
                ;;
            [eE])
                error "Bootstrap aborted."
                ;;
            *)
                echo "Please press [c] to continue or [e] to exit."
                ;;
            esac
        done

    }

    ask_background() {
        row
        info "Do you want to include the default wallpaper from ${YELLOW}${GITHUB_OWNER}/${GITHUB_REPOSITORY}?${NC}"
        warn "If not, you must save yours under ${BLUE}\$HOME/Pictures/wallpaper.jpg${NC}"
        row

        info "Press [y] to add or [s] to skip:"
        while true; do
            read -r choice
            case $choice in
            [sS])
                info "Skipping $GITHUB_OWNER/$GITHUB_REPOSITORY background."
                return 0
                ;;
            [yY])
                mkdir -p "$WALLPAPER_DIR"
                make init && cp -f static/wallpaper.jpg "$WALLPAPER_DIR"
                info "Saved successfully! If you want to set your own, remember"
                info "to replace: ${BLUE}\$HOME/Pictures/wallpaper.jpg${NC}"
                return 0
                ;;
            *)
                echo "Please press [y] to save it or [s] to skip."
                ;;
            esac
        done
    }

    ask_base() {
        row
        info "You are about to install ${YELLOW}${GITHUB_OWNER}/${GITHUB_REPOSITORY}${NC}${BOLD} package baseline."
        info "This process requires temporary ${RED}sudo${NC}${BOLD} privileges and"
        info "will ask for your preferences."
        row

        info "Press [c] to continue, [s] to skip or [e] to exit:"
        while true; do
            read -r choice
            case $choice in
            [sS])
                info "Skipping $GITHUB_OWNER/$GITHUB_REPOSITORY baseline packages."
                return 0
                ;;
            [eE])
                error "Baseline bootstrap aborted."
                ;;
            [cC])
                make base || error "Failed to run 'make base'"
                return 0
                ;;
            *)
                echo "Please press [c] to continue, [s] to skip or [e] to exit."
                ;;
            esac
        done
    }

    ask_stow() {
        row
        info "Do you want to include symbolic links from ${YELLOW}${GITHUB_OWNER}/${GITHUB_REPOSITORY}${NC}"
        info "to your ${YELLOW}\$HOME${NC} and ${YELLOW}\$HOME/.config${NC}${BOLD} directories?"
        warn "Existing files at these locations may cause conflicts and"
        warn "will require to rename or move them prior to rerun this task."
        row

        info "Press [c] to continue or [s] to skip:"
        while true; do
            read -r choice
            case $choice in
            [sS])
                info "Skipping $GITHUB_OWNER/$GITHUB_REPOSITORY stow."
                return 0
                ;;
            [cC])
                make stow || error "Failed to run 'make stow'"
                return 0
                ;;
            *)
                echo "Please press [c] to continue or [s] to skip."
                ;;
            esac
        done
    }

    ask_mise_neovim() {
        row
        info "Let's finish the bootstrap process by installing ${BLUE}mise${NC} ${BOLD}system-wide"
        info "dependencies and setup ${BLUE}Neovim${NC}. ${BOLD}It might take a while"
        info "but wait for the task to finish before opening the editor."
        row

        info "Press [c] to continue or [s] to skip: "
        while true; do
            read -r choice
            case $choice in
            [sS])
                info "Skipping $GITHUB_OWNER/$GITHUB_REPOSITORY mise and neovim hooks."
                return 0
                ;;
            [cC])
                if [ ! -s "$XDG_CONFIG_HOME/mise/config.tomls" ] || [ ! -s "$XDG_CONFIG_HOME/nvim/init.lua" ]; then
                    error "Oops! You must symlink ${YELLOW}${GITHUB_OWNER}/${GITHUB_REPOSITORY}${NC} ${BOLD}to proceed."
                fi
                make mise || error "Failed to run 'make mise'"
                make neovim || error "Failed to run 'make neovim'"
                return 0
                ;;
            *)
                echo "Please press [c] to continue or [s] to skip."
                ;;
            esac
        done
    }

    main() {
        require_os
        require_dependencies
        mkdir -p "$XDG_CACHE_HOME"
        checkout \
            "$GITHUB_BASE_URL/$GITHUB_OWNER/$GITHUB_REPOSITORY.git" \
            "$XDG_CACHE_HOME/$GITHUB_REPOSITORY" \
            "$GITHUB_BRANCH"
        (
            cd "$XDG_CACHE_HOME/$GITHUB_REPOSITORY"
            ask_background
            ask_base
            ask_stow
            ask_mise_neovim
            info "Installation complete! You may need to restart your shell"
            info "with: ${GREEN}exec \$SHELL -i${NC} ${BOLD}or run: ${GREEN}source ~/.bashrc${NC}"
        )
    }

    main
}
