#!/usr/bin/env bash

set -ueo pipefail

REPOSITORY_ROOTDIR=$(realpath "$(dirname -- "${BASH_SOURCE[0]}")/../..")
readonly REPOSITORY_ROOTDIR

source "$REPOSITORY_ROOTDIR/bin/common/logging"

SCREENSHOT=$(mktemp --suffix=.png)

trap 'rm -f "$SCREENSHOT"' EXIT INT QUIT TERM

TEXT_OVERLAY="Type password to unlock"
TEXT_OVERLAY_FONT="JetBrainsMono-NF-ExtraBold"
TEXT_OVERLAY_FONT_SIZE=42
TEXT_OVERLAY_XY_POSITION="+0+160"
I3LOCK_BAR_ENABLED=0

readonly BLACK='000000' WHITE='ffffff' GREY='242121' RED='f38ba8' YELLOW='f9e2af'
readonly ALPHA_0='00' ALPHA_10='1A' ALPHA_20='33' ALPHA_30='4D' ALPHA_40='66' ALPHA_60='99' ALPHA_70='B3'
readonly BRIGHTNESS_THRESHOLD=60 HIDDEN="${BLACK}${ALPHA_0}"

readonly WAYLAND_SESSION_TYPE="wayland"
readonly X11_SESSION_TYPE="x11"

show_options() {
    awk '{$1=$1};1' <<-EOF
        Usage: $(basename "$0") [OPTION]...

        -f, --font       The text font to use. default: $TEXT_OVERLAY_FONT
        -s, --size       The text font size. default: $TEXT_OVERLAY_FONT_SIZE
        -t, --text       The text to display on the screen. default: $TEXT_OVERLAY
        -p, --position   The X:Y text position relative to the center of the screen. default: $TEXT_OVERLAY_XY_POSITION
        -b, --bar        Replace i3lock ring and use the bar flavour instead.
        -h, --help       Display this help message and exit.
EOF
}

require_cmd() {
    if ! command -v "$1" &>/dev/null; then
        log::error "command: $1 not found"
    fi
}

: "${XDG_SESSION_TYPE:=}"

case $XDG_SESSION_TYPE in
"$WAYLAND_SESSION_TYPE")
    require_cmd "grim"
    SESSION_TYPE="$WAYLAND_SESSION_TYPE"
    SCREENSHOT_CMD=(grim "$SCREENSHOT")
    ;;
"$X11_SESSION_TYPE")
    require_cmd "import"
    SESSION_TYPE="$X11_SESSION_TYPE"
    SCREENSHOT_CMD=(import -silent -window root "$SCREENSHOT")
    ;;
*)
    log::error "Unknown XDG_SESSION_TYPE"
    ;;
esac

readonly SESSION_TYPE

while [[ $# -gt 0 ]]; do
    case $1 in
    -f | --font)
        FONT_LIST=$(magick -list font | awk -F': ' '/Font:/ { print $2 }')
        if ! echo "$FONT_LIST" | grep -qx "$2"; then
            log::error "'$2' is not a recognized font. Check your supported fonts with: ${GREEN}magick -list font${NC}"
        fi
        TEXT_OVERLAY_FONT="$2"
        shift 2
        ;;
    -s | --size)
        TEXT_OVERLAY_FONT_SIZE="$2"
        shift 2
        ;;
    -t | --text)
        TEXT_OVERLAY="$2"
        shift 2
        ;;
    -p | --position)
        TEXT_OVERLAY_XY_POSITION="$2"
        shift 2
        ;;
    -b | --bar)
        [[ $SESSION_TYPE == "$X11_SESSION_TYPE" ]] || log::error "${GREEN}-b|--bar${NC} is an ${RED}x11${NC} exclusive option"
        I3LOCK_BAR_ENABLED=1
        shift
        ;;
    -h | --help)
        show_options
        exit 0
        ;;
    *)
        echo "$(basename "$0"): invalid option: $1"
        show_options
        exit 1
        ;;
    esac
done

"${SCREENSHOT_CMD[@]}"
readonly SCREENSHOT

SCREENSHOT_AVG_BRIGHTNESS_PERCENTAGE=$(magick "$SCREENSHOT" -gravity center -crop 100x100+0+0 +repage \
    -colorspace HSB -channel B -format "%[fx:int(mean*100)]" info:)
readonly SCREENSHOT_AVG_BRIGHTNESS_PERCENTAGE

if [[ "$SCREENSHOT_AVG_BRIGHTNESS_PERCENTAGE" -gt "$BRIGHTNESS_THRESHOLD" ]]; then
    PRIMARY_COLOR=$BLACK
    SECONDARY_COLOR=$WHITE
else
    PRIMARY_COLOR=$WHITE
    SECONDARY_COLOR=$BLACK
fi

readonly PRIMARY_COLOR SECONDARY_COLOR

declare -A PADLOCK_ICONS_MAPPING=(
    [$BLACK]="${REPOSITORY_ROOTDIR}/static/icons/coffee-dark.png"
    [$WHITE]="${REPOSITORY_ROOTDIR}/static/icons/coffee-white.png"
)

readonly PADLOCK_ICON="${PADLOCK_ICONS_MAPPING[$PRIMARY_COLOR]}"

PADLOCK_ICON_WIDTH=$(identify -format "%w" "$PADLOCK_ICON")
read -r SCREENSHOT_WIDTH SCREENSHOT_HEIGHT <<<"$(identify -format "%w %h" "$SCREENSHOT")"
readonly SCREENSHOT_WIDTH SCREENSHOT_HEIGHT PADLOCK_ICON_WIDTH

declare -a LOCK_OPTS=(
    "--inside-color=${PRIMARY_COLOR}${ALPHA_20}"
    "--ring-color=${PRIMARY_COLOR}${ALPHA_40}"
    "--line-color=${PRIMARY_COLOR}${ALPHA_10}"
    "--separator-color=${GREY}${ALPHA_20}"
    "--ignore-empty-password"
)

declare -a I3LOCK_OPTS=(
    "--ringver-color=${YELLOW}${ALPHA_70}"
    "--ringwrong-color=${RED}${ALPHA_70}"
    "--insidever-color=${YELLOW}${ALPHA_30}"
    "--insidewrong-color=${RED}${ALPHA_30}"
    "--verif-color=${HIDDEN}"
    "--wrong-color=${HIDDEN}"
    "--keyhl-color=${SECONDARY_COLOR}${ALPHA_60}"
    "--bshl-color=${SECONDARY_COLOR}${ALPHA_60}"
    "--radius=$((PADLOCK_ICON_WIDTH - 20))"
    "--screen=1"
    "--indicator"
)
declare -a SWAYLOCK_OPTS=(
    "--ring-ver-color=${YELLOW}${ALPHA_70}"
    "--ring-wrong-color=${RED}${ALPHA_70}"
    "--ring-clear-color=${YELLOW}${ALPHA_70}"
    "--line-ver-color=${YELLOW}${ALPHA_70}"
    "--line-wrong-color=${RED}${ALPHA_70}"
    "--line-clear-color=${YELLOW}${ALPHA_70}"
    "--inside-ver-color=${YELLOW}${ALPHA_30}"
    "--inside-wrong-color=${RED}${ALPHA_30}"
    "--inside-clear-color=${YELLOW}${ALPHA_40}"
    "--key-hl-color=${SECONDARY_COLOR}${ALPHA_60}"
    "--bs-hl-color=${SECONDARY_COLOR}${ALPHA_60}"
    "--text-ver-color=${HIDDEN}"
    "--text-wrong-color=${HIDDEN}"
    "--text-clear-color=${HIDDEN}"
    "--indicator-radius=$((PADLOCK_ICON_WIDTH - 20))"
    "--indicator-idle-visible"
    "--hide-keyboard-layout"
    "--disable-caps-lock-text"
)

readonly I3LOCK_BAR_WIDTH=200
I3LOCK_X_POSITION=$(((SCREENSHOT_WIDTH / 2) - (I3LOCK_BAR_WIDTH / 2)))
I3LOCK_Y_POSITION=$(((SCREENSHOT_HEIGHT / 2) + 100))
readonly I3LOCK_X_POSITION I3LOCK_Y_POSITION

readonly -a I3LOCK_BAR_OPTS=(
    "--bar-indicator"
    "--bar-direction=1"
    "--bar-count=100"
    "--bar-base-width=20"
    "--bar-max-height=20"
    "--bar-color=${PRIMARY_COLOR}${ALPHA_30}"
    "--bar-pos=${I3LOCK_X_POSITION}:${I3LOCK_Y_POSITION}"
    "--bar-total-width=${I3LOCK_BAR_WIDTH}"
)

if [[ "$I3LOCK_BAR_ENABLED" -eq 1 ]]; then
    I3LOCK_OPTS+=("${I3LOCK_BAR_OPTS[@]}")
fi

if [[ $SESSION_TYPE == "$WAYLAND_SESSION_TYPE" ]]; then
    LOCK_CMD="swaylock"
    LOCK_OPTS+=("${SWAYLOCK_OPTS[@]}")
else
    LOCK_CMD="i3lock"
    LOCK_OPTS+=("${I3LOCK_OPTS[@]}")
fi

declare -ra LOCK_SCREEN_GAMMA_ADJUSTMENT_ARGS=(-level "0%,100%,0.6")
declare -ra LOCK_SCREEN_IMAGE_EFFECT_ARGS=(-scale 20% +noise Uniform -attenuate 0.7 -scale 500%)
declare -ra LOCK_SCREEN_OVERLAY_TEXT_ARGS=(-font "$TEXT_OVERLAY_FONT" -pointsize "$TEXT_OVERLAY_FONT_SIZE" -fill "#${PRIMARY_COLOR}" -gravity center -annotate "$TEXT_OVERLAY_XY_POSITION" "$TEXT_OVERLAY")
declare -ra LOCK_SCREEN_OVERLAY_ICON_ARGS=("$PADLOCK_ICON" -gravity center -composite)

magick "$SCREENSHOT" \
    "${LOCK_SCREEN_GAMMA_ADJUSTMENT_ARGS[@]}" \
    "${LOCK_SCREEN_IMAGE_EFFECT_ARGS[@]}" \
    "${LOCK_SCREEN_OVERLAY_TEXT_ARGS[@]}" \
    "${LOCK_SCREEN_OVERLAY_ICON_ARGS[@]}" \
    "$SCREENSHOT"

require_cmd $LOCK_CMD && "$LOCK_CMD" -i "$SCREENSHOT" "${LOCK_OPTS[@]}"
