-- Color Scheme
vim.cmd("colorscheme " .. vim.g.neovim_colorscheme)

--- Import Plugins config
require("plugins.avante")
require("plugins.cmp")
require("plugins.dap")
require("plugins.mason")
require("plugins.linters")
require("plugins.formatter")
require("plugins.dev")
require("plugins.lsp")
require("plugins.mini")
require("plugins.misc")
require("plugins.neogen")
require("plugins.neogit")
require("plugins.neotree")
require("plugins.noice")
require("plugins.snacks")
require("plugins.statusline")
require("plugins.tabby")
require("plugins.telescope")
require("plugins.terminal")
require("plugins.treesitter")
require("plugins.windows")
require("plugins.diagnostic")
