#!/usr/bin/env bash

set -ueo pipefail

#MISE hide=true

readonly GITHUB_CLI_EXTENSIONS=(
    "meiji163/gh-notify"
)

add_github_extensions() {
    for GITHUB_CLI_EXTENSION in "${GITHUB_CLI_EXTENSIONS[@]}"; do
        gh extension install "$GITHUB_CLI_EXTENSION"
    done
}

if [[ -z ${GITHUB_TOKEN:-} && -s "$HOME/.GITHUB_TOKEN" ]]; then
    gh auth login --with-token <"$HOME/.GITHUB_TOKEN"
fi

if gh auth status &>/dev/null; then
    add_github_extensions
fi
