#!/usr/bin/env bash

set -ueo pipefail

REPOSITORY_ROOTDIR=$(realpath "$(dirname -- "${BASH_SOURCE[0]}")/../..")
readonly REPOSITORY_ROOTDIR

source "${REPOSITORY_ROOTDIR}/bin/common/logging"

TEXT_OVERLAY="Type password to unlock"
TEXT_OVERLAY_FONT="Adwaita-Mono-Bold"
TEXT_OVERLAY_FONT_SIZE=42
TEXT_OVERLAY_XY_POSITION="+0+160"
I3LOCK_BAR_ENABLED=0

function show_options() {
    awk '{$1=$1};1' <<- EOF
        Usage: $(basename "$0") [OPTION]...

        -f, --font       The text font to use. default: $TEXT_OVERLAY_FONT
        -s, --size       The text font size. default: $TEXT_OVERLAY_FONT_SIZE
        -t, --text       The text to display on the screen. default: $TEXT_OVERLAY
        -p, --position   The X:Y text position relative to the center of the screen. default: $TEXT_OVERLAY_XY_POSITION
        -b, --bar        Replace i3lock ring and use the bar flavour instead.
        -h, --help       Display this help message and exit.
EOF
}

while [[ $# -gt 0 ]]; do
    case $1 in
    -f | --font)
        FONT_LIST=$(magick -list font | awk -F': ' '/Font:/ { print $2 }')
        if ! echo "$FONT_LIST" | grep -qx "$2"; then
            log::error "'$2' is not a recognized font. Please list valid fonts using: ${GREEN}magick -list font${NC}"
        fi
        TEXT_OVERLAY_FONT="$2"
        shift 2
        ;;
    -s | --size)
        TEXT_OVERLAY_FONT_SIZE="$2"
        shift 2
        ;;
    -t | --text)
        TEXT_OVERLAY="$2"
        shift 2
        ;;
    -p | --position)
        TEXT_OVERLAY_XY_POSITION="$2"
        shift 2
        ;;
    -b | --bar)
        I3LOCK_BAR_ENABLED=1
        shift
        ;;
    -h | --help)
        show_options
        exit 0
        ;;
    *)
        echo "$(basename "$0"): invalid option: $1"
        show_options
        exit 1
        ;;
    esac
done

readonly \
    TEXT_OVERLAY_FONT \
    TEXT_OVERLAY_FONT_SIZE \
    TEXT_OVERLAY TEXT_OVERLAY_XY_POSITION \
    I3LOCK_BAR_ENABLED

SCREENSHOT=$(mktemp --suffix=.png)
readonly SCREENSHOT

trap 'rm -f "$SCREENSHOT"' EXIT INT QUIT TERM

import -silent -window root "$SCREENSHOT"

readonly BLACK='000000' WHITE='ffffff' GREY='242121' RED='f38ba8' YELLOW='f9e2af'
readonly ALPHA_0='00' ALPHA_10='1A' ALPHA_20='33' ALPHA_30='4D' ALPHA_40='66' ALPHA_60='99' ALPHA_70='B3'
readonly BRIGHTNESS_THRESHOLD=60

# 100x100-pixel center crop and measure the resulting area's average brightness expressed as a percentage.
SCREENSHOT_AVG_BRIGHTNESS_PERCENTAGE=$(magick "$SCREENSHOT" -gravity center -crop 100x100+0+0 +repage \
    -colorspace HSB -channel B -format "%[fx:int(mean*100)]" info:)
readonly SCREENSHOT_AVG_BRIGHTNESS_PERCENTAGE

if [[ "$SCREENSHOT_AVG_BRIGHTNESS_PERCENTAGE" -gt "$BRIGHTNESS_THRESHOLD" ]]; then
    PRIMARY_COLOR=$BLACK
    SECONDARY_COLOR=$WHITE
else
    PRIMARY_COLOR=$WHITE
    SECONDARY_COLOR=$BLACK
fi

readonly PRIMARY_COLOR SECONDARY_COLOR

declare -A PADLOCK_ICONS_MAPPING=(
    [$BLACK]="${REPOSITORY_ROOTDIR}/static/icons/monkey-dark.png"
    [$WHITE]="${REPOSITORY_ROOTDIR}/static/icons/monkey-white.png"
)

readonly PADLOCK_ICON="${PADLOCK_ICONS_MAPPING[$PRIMARY_COLOR]}"
readonly TEXT_OVERLAY_COLOR="#${PRIMARY_COLOR}"

declare -a I3LOCK_COLOR_OPTS=(
    "--inside-color=${PRIMARY_COLOR}${ALPHA_20}"
    "--ring-color=${PRIMARY_COLOR}${ALPHA_40}"
    "--line-color=${PRIMARY_COLOR}${ALPHA_10}"
    "--keyhl-color=${SECONDARY_COLOR}${ALPHA_60}"
    "--separator-color=${GREY}${ALPHA_20}"
    "--ringver-color=${YELLOW}${ALPHA_70}"
    "--ringwrong-color=${RED}${ALPHA_70}"
    "--insidever-color=${YELLOW}${ALPHA_30}"
    "--insidewrong-color=${RED}${ALPHA_30}"
    "--verif-color=${SECONDARY_COLOR}${ALPHA_0}"
    "--wrong-color=${SECONDARY_COLOR}${ALPHA_0}"
    "--bshl-color=${SECONDARY_COLOR}${ALPHA_60}"
)

IFS='x' read -r SCREENSHOT_WIDTH SCREENSHOT_HEIGHT <<<"$(identify -format "%wx%h" "$SCREENSHOT")"
readonly SCREENSHOT_WIDTH SCREENSHOT_HEIGHT

readonly I3LOCK_BAR_WIDTH=200
I3LOCK_X_POSITION=$(((SCREENSHOT_WIDTH / 2) - (I3LOCK_BAR_WIDTH / 2)))
I3LOCK_Y_POSITION=$(((SCREENSHOT_HEIGHT / 2) + 100))
readonly I3LOCK_X_POSITION I3LOCK_Y_POSITION

readonly -a I3LOCK_BAR_OPTS=(
    "--bar-indicator"
    "--bar-direction=1"
    "--bar-count=100"
    "--bar-base-width=20"
    "--bar-max-height=20"
    "--bar-color=${PRIMARY_COLOR}${ALPHA_30}"
    "--bar-pos=${I3LOCK_X_POSITION}:${I3LOCK_Y_POSITION}"
    "--bar-total-width=${I3LOCK_BAR_WIDTH}"
)

if [[ "$I3LOCK_BAR_ENABLED" -eq 1 ]]; then
    I3LOCK_COLOR_OPTS+=("${I3LOCK_BAR_OPTS[@]}")
fi

declare -ra LOCK_SCREEN_GAMMA_ADJUSTMENT_ARGS=(-level "0%,100%,0.6")
declare -ra LOCK_SCREEN_BLUR_EFFECT_ARGS=(-filter Gaussian -resize 20% -define "filter:sigma=1.5" -resize 500%)
declare -ra LOCK_SCREEN_OVERLAY_TEXT_ARGS=(-font "$TEXT_OVERLAY_FONT" -pointsize "$TEXT_OVERLAY_FONT_SIZE" -fill "$TEXT_OVERLAY_COLOR" -gravity center -annotate "$TEXT_OVERLAY_XY_POSITION" "$TEXT_OVERLAY")
declare -ra LOCK_SCREEN_OVERLAY_ICON_ARGS=("$PADLOCK_ICON" -gravity center -composite)

magick "$SCREENSHOT" \
    "${LOCK_SCREEN_GAMMA_ADJUSTMENT_ARGS[@]}" \
    "${LOCK_SCREEN_BLUR_EFFECT_ARGS[@]}" \
    "${LOCK_SCREEN_OVERLAY_TEXT_ARGS[@]}" \
    "${LOCK_SCREEN_OVERLAY_ICON_ARGS[@]}" \
    "$SCREENSHOT"

i3lock -i "$SCREENSHOT" "${I3LOCK_COLOR_OPTS[@]}" &>/dev/null
